# COMMANDS
alias sb.='source ~/.bashrc'
alias vb.='vim ~/.bashrc'
alias vprof.='vim ~/.bash_profile'
alias C='clear'
alias nf='neofetch'

alias pyhost='py -m http.server'

#########################################################


# Python 3.10
alias python='winpty ~/AppData/Local/Programs/Python/Python310/python.exe'
alias py='winpty ~/AppData/Local/Programs/Python/Python310/python.exe'

# Mozilla Firefox
alias firefox='winpty C:/"Program Files"/"Mozilla Firefox"/firefox.exe'

# Google Chrome
alias chrome='winpty C:/"Program Files"/Google/Chrome/Application/chrome.exe'

# Microsoft Edge
alias edge='winpty C:/"Program Files (x86)"/Microsoft/Edge/Application/msedge.exe'

# Thonny
alias thonny='winpty ~/AppData/Local/Programs/Thonny/thonny.exe'

# Atom
alias atom='winpty ~/AppData/Local/atom/atom.exe'

# PyCharm
alias pycharm='winpty D:/"@qwzz"/Apps/"PyCharm Community Edition 2021.2.3"/bin/pycharm64.exe'

# Figma
alias figma='winpty C:/Users/"Pro Komputer"/AppData/Local/Figma/Figma.exe'

# LibreOffice
alias libre='winpty C:/"Program Files"/LibreOffice/program/soffice.exe'

# VLC
alias vlc='winpty C:/"Program Files (x86)"/VideoLAN/VLC/vlc.exe'

# Free Download Manager
alias fdm='winpty C:/"Program Files"/Softdeluxe/"Free Download Manager"/fdm.exe'

# XNConvert
alias xnconvert='winpty C:/"Program Files"/XnConvert/xnconvert.exe'
alias xnc='winpty C:/"Program Files"/XnConvert/xnconvert.exe'

# Glasswire
alias glasswire='winpty C:/"Program Files (x86)"/GlassWire/GlassWire.exe'

# Steam
alias steam='winpty C:/"Program Files (x86)"/Steam/steam.exe'

# Discord
alias discord='winpty ~/AppData/Local/Discord/Update.exe'

# Zoom
alias zoom='winpty ~/AppData/Roaming/Zoom/bin/Zoom.exe'

# Droid Cam Client
alias droidcam='winpty C:/"Program Files (x86)"/DroidCam/DroidCamApp.exe'
alias dcc='winpty C:/"Program Files (x86)"/DroidCam/DroidCamApp.exe'

# Faststone Image Viewer
alias faststone='winpty C:/"Program Files (x86)"/"FastStone Image Viewer"/FSViewer.exe'
alias fss='winpty C:/"Program Files (x86)"/"FastStone Image Viewer"/FSViewer.exe'

# XNView
alias xnview='winpty C:/"Program Files (x86)"/XnView/xnview.exe'
alias xnv='winpty C:/"Program Files (x86)"/XnView/xnview.exe'

# Adobe
alias photoshop='winpty C:/"Program Files"/Adobe/"Adobe Photoshop 2021"/Photoshop.exe'
alias premiere='winpty C:/"Program Files"/Adobe/"Adobe Premiere Pro 2020"/"Adobe Premiere Pro.exe"'
alias illustrator='winpty C:/"Program Files"/Adobe/"Adobe Illustrator 2021"/"Support Files"/Contents/Windows/Illustrator.exe'

# Online
alias github='start "https://github.com/"'
alias gmail='start "https://mail.google.com/"'
alias devto='start "https://dev.to/"'
alias youtube='start "https://youtube.com/"'
alias youtubestd='start "https://studio.youtube.com/"'
alias gdrive='start "https://drive.google.com/"'
alias whatsapp='start "https://web.whatsapp.com/"'